spring.application.name=KRASky
# 1. Configuración de la conexión a la Base de Datos 'krasky'
spring.datasource.url=jdbc:mysql://localhost:3306/krasky?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==============================================================
# CONFIGURACIÓN DE SEGURIDAD (SKYBOOKING)
# ==============================================================

# Clave secreta para firmar los tokens JWT (Base64)
app.jwt.secret=TUlDbGF2ZVNlY3JldGFNdX1MYXJnYVBhcmFKV1QyNTZCaXRzQ29tb01pbmltbzEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MA==

# Tiempo de expiración del token JWT (24 horas en milisegundos)
app.jwt.expiration=86400000

# Tiempo de expiración de la sesión WEB (30 minutos)
server.servlet.session.timeout=30m

logging.level.org.springframework.security=DEBUG